In [ ]:
import pandas as pd  
import numpy as np 
import datetime
from datetime import datetime,date 
import matplotlib.pyplot as plt 
pd.set_option('display.notebook_repr_html',True) 
pd.set_option('display.max_columns',7) 
pd.set_option('display.max_rows',10) 
pd.set_option('display.width',250) 
%matplotlib inline 
from re import match 
import os 
import json 

'''
<요구사항1>
다음의 순서대로 코딩하세요.
가. 보기의 jumsu 딕셔너리 중에서 평균 점수가 60점 미만인 사람만 선별하여 또 다른 딕셔너리에 저장하세요.
나. 가. 항에서 만든 또 다른 딕셔너리를 이용하여 데이터(요소)가 평균이고 인덱스가 이름인 Series 를 만드세요.
다. 시리즈를 <실행결과> 와 같이 출력하세요.

<실행결과>

홍길동-홍길도-강감도-유관도-홍길재-강감재-유관재-
53.33--48.33--54.33--53.33--48.67--54.67--53.67--
'''

jumsu = {
'홍길동' : [50,60,50],
'이순동' : [60,60,60],
'강감동' : [100,90,90],
'유관동' : [80,80,90],
'홍길도' : [50,45,50],
'이순도' : [80,70,66],
'강감도' : [64,49,50],
'유관도' : [60,50,50],
'홍길재' : [50,45,51],
'이순재' : [80,70,61],
'강감재' : [64,49,51],
'유관재' : [60,50,51],
'강환석' : [95,95,95]
}

jumsu2 =  {} 
for key,value in jumsu.items():
    if round(np.mean(value)) <60: 
        jumsu2[key] = round(np.mean(value))

jumsu3= {key:round(np.mean(value),2) for key,value in jumsu.items() if round(np.mean(value),2)< 60} 
jumsu3_s= pd.Series(jumsu3) 
print(jumsu3)

### === 위 평균 60점 미만 사람들의 총점을 구하여 이름과 총점으로 딕셔너리를 생성
## 그리고 딕셔너리로 시리즈를 만드세요. 
'''
jumsu4= {}
for key, value in jumsu.items(): 
    if round(np.mean(value))<60: 
        jumsu4[key] = round(np.sum(value)) 

jumsu4 = pd.Series(jumsu4)
''' 
## or
jumsu4= { key:np.sum(value) for key,value in jumsu.items() if round(np.mean(value),2)< 60} 
jumsu4_s= pd.Series(jumsu4)

jumsu_df= pd.DataFrame({'합계': jumsu4_s,"평균": jumsu3_s}) 
print(jumsu_df)
print(jumsu_df.index) 
print(jumsu_df['합계'])
print(jumsu_df['평균'])

#홍길도의 평균값만 출력
print(jumsu_df['평균']['홍길도']) #48.33

'''
##여기 한번 더 보자 
for i in jumsu_df.index:
    print(i)
    if i=='홍길도':
        print(i)
'''

In [ ]:
##날짜 데이터 생성
dates= pd.date_range('2022-04-01','2022-04-07')
print(dates,type(dates)) 

##datetime 이라는 특별한 형식 인덱스를 생성함 
# datetime은 판다스에서 날짜/시간 관련 인덱스  
temp1= pd.Series([80,82,85,90,92,87,88],index=dates) 
temp2= pd.Series([60,70,69,83,77,79,75],index=dates)
temp1.info()  
##pandas 에서 DatetimeIndex의 형식으로 인덱스를 사용하는 데이터를 시계열이라고 한다. 
temp1['2022-04-07'] #88 

##temp1 도시의 온도와 temp2 도시의 온도간 차이를 temp_diff로 저장 
temp_diff= temp1-temp2 
print(temp_diff, type(temp_diff)) #시리즈에서 시리즈를 뺐으니 그대로 반환값은 시리즈이다 

temp_diff.mean() #numpy에서 제공하는 라이브러리 mean()과 구분되는 mean이 존재 #13

#위 temp1,temp2이용하여 뺄셈외 다른 연산이 가능한지 실습
temp_sum= temp1+temp2 
temp_mul= temp1*temp2 
temp_div= temp1/temp2
print(temp_sum,temp_mul,temp_div)

#temp3를 생성, temp1과 temp2과 대응하는 시리즈 생성
#생성된 temp1,2,3 temps_df로 데이터프레임 생성하세요.
#temp1 - Missoula temp2- Philadelphia, temp3- Seoul   
temp3= pd.Series([75,77,67,82,77,85,89],index= dates) 

temp_df = pd.DataFrame({'Missoula':temp1,'Philadelphia':temp2,'Seoul':temp3})
print(temp_df)

## or 
# dic = {'Missoula':temp1,'Philadelphia':temp2,'Seoul':temp3}
# temp_df = pd.DataFrame(dic) 
print('='*50) 
avg1= round(np.mean(temp_df['Missoula']),2) 
avg2= round(np.mean(temp_df['Philadelphia']),2) 
avg3= round(np.mean(temp_df['Seoul']),2) 
state= ['Missoula','Philadelphia','Seoul']
# index= ['Missoula','Philadelphia','Seoul']
#문제3- 각도의 평균 온도를 구하세요  
avg= pd.Series([avg1,avg2,avg3],index= ['Missoula','Philadelphia','Seoul']) #또는 index=state 
print(avg)

#시리즈 1개 호출 => Return Series 
#시리즈 2개 호출 => Return DataFrame 
cc= temp_df[['Missoula','Philadelphia']]
print(cc,type(cc)) 
dif= cc['Missoula']-cc['Philadelphia']

cc['Difference'] = dif 

print(cc)

##temp_df 또는 cc 데이터프레임의 컬럼명을 모두 출력 
cc.index
cc.values
cc.columns #Index(['Missoula', 'Philadelphia', 'Difference(Missoula-Philadelphia)'], dtype='object')
# columns => 데이터프레임에 있는 컬럼을 출력 

# 데이터프레임의 인덱스는 기본 인덱스와 사용자 인덱스가 존재한다.
# 기본 인덱스는 위치 인덱스라고도 한다.
# cc또는 temp_df에 있는 2022-04-01~2022-04-07의 인덱스는 사용자인덱스라고 한다.
# 슬라이싱 이용한 방식은 기본 인덱스를 사용하게 된다. 
cc.Difference[1:4]
cc[1:4]
cc[:3]
cc[3:]
cc[-2:]
cc[-1:]

## label을 이용하는 접근(label은 사용자 정의 인덱스를 말함
# 접근법 
# 1. 단일: [DataFrame or Series].loc['label명']
# DataFrame 
temp_df.loc['20220401']
temp_df.loc['20220401',['Missoula','Seoul']]
# Series 
temp_df.Seoul.loc['20220401']

# 2.여러개일 경우(특정 인덱스만 출력)
# DataFrame 
temp_df.loc[['20220404','20220406'],['Seoul','Philadelphia']]
# Series 
temp_df.Seoul.loc[['20220402','20220406']]

cc.loc['2022-04-04':'2022-04-07']
cc.Philadelphia.loc['2022-04-04':'2022-04-07']
temp_df.loc['2022-04-04':'2022-04-07']

# 3.여러개일 경우(연속된 값의 경우) 
# DataFrame
temp_df.loc['20220404':'20220406',['Seoul','Philadelphia']]  #Dash의 유뮤는 상관 x 

ls= [True,False,False,True,False,False,True]
temp_df.loc[ls,['Philadelphia','Seoul']]
# Series 
temp_df.Missoula.loc[ls]

# 기본 인덱스를 이용하여 접근 
# 1. 단일 : [데이터프레임 or Series].iloc[index값(int)]

# DataFrame
print(cc.iloc[3:,1])   # 컬럼의 1번째 인덱스인 Seoul의 [3:] 출력 
print('-'*50)
print(cc.iloc[3])      # 인덱스가 3인 행 출력
print('-'*50)
print(temp_df.iloc[3,1])    # 인덱스가 3인 행, 인덱스가 1인 열의 값 출력     # 82
# Series
print(temp_df.Seoul.iloc[3])       # Seoul 열(시리즈)의 인덱스가 3인 행 출력 # 82

# 2. 여러개일 경우(특정 인덱스만 출력)

# DataFrame
print(temp_df.iloc[[1,3,5],[1,2]]) # cc.iloc[[출력할 행], [출력할 열]]
print('-'*50)
# Series
print(temp_df.Seoul.iloc[[1,3,5]])

# 2-2. 여러개일 경우(연속된 값인 경우)
# DataFrame
print(temp_df.iloc[1:4,[0,2]])
print('-'*50)
# Series
print(temp_df.Seoul.iloc[3:])

# 4. Boolean 값을 이용한 출력
# DataFrame
print(cc.iloc[ls,[0,1,2]])
print('-'*50)
# Series
print(temp_df.Seoul.loc[ls])

In [150]:
df31= pd.read_csv("data/data/goog.csv",parse_dates= ['Date'],index_col= 'Date')
df31.info

<bound method DataFrame.info of                   Open        High         Low       Close   Volume
Date
2016-12-19  790.219971  797.659973  786.270020  794.200012  1225900
2016-12-20  796.760010  798.650024  793.270020  796.419983   925100
2016-12-21  795.840027  796.676025  787.099976  794.559998  1208700
2016-12-22  792.359985  793.320007  788.580017  791.260010   969100
2016-12-23  790.900024  792.739990  787.280029  789.909973   623400
...                ...         ...         ...         ...      ...
2017-03-13  844.000000  848.684998  843.250000  845.539978  1149500
2017-03-14  843.640015  847.239990  840.799988  845.619995   779900
2017-03-15  847.590027  848.630005  840.770020  847.200012  1379600
2017-03-16  849.030029  850.849976  846.130005  848.780029   970400
2017-03-17  851.609985  853.400024  847.109985  852.119995  1712300

[61 rows x 5 columns]>

In [151]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 KB 1.7 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2
Note: you may need to restart the kernel to use updated packages.