In [ ]:
# Selenium 의 사용이유: 로그인이 필요한 Session 정보가 필요한 경우 사용하게 된다. 
# Selenium을 통해서 DOM 요소 추출 
## 메서드_여러개 중에서 처음 요소를 추출 
#find_element_by_id(id): id 속성으로 요소 하나추출 
#find_element_by_name(name): name속성으로 요소를 하나추출  
#find_element_by_css_selector(query): CSS 선택자로 요소를 하나추출  
#find_element_by_xpath(query): Xpath를 지정해 요소를 하나추출 
#find_element_by_tag_name(name): 태그 이름에 해당하는 요소를 하나추출 
#find_element_by_link_text(text): 링크 텍스트로 요소를 하나추출 
#find_element_by_partial_link_text(text): 링크의 자식요소에 포함된 텍스트 요소로 하나추출
#find_element_by_class_name(name): 클래스 이름에 해당하는 요소를 하나추출 

# 모든 요소를 추출 
#find_elements_by_css_selector(query): CSS 선택자로 모든 요소추출 
#find_elements_by_xpath(query): Xpath를 지정해 모든 요소추출  
#find_elements_by_tag_name(name): 태그명에 해당하는 모든 요소추출
#find_elements_by_partial_link_text(text): 링크의 자식요소에 모든 요소추출 

# NoSuchElementException 이라는 예외는 해당 요소를 찾지 못한 경우 발생함 

from selenium import webdriver

path = "/usr/local/bin/chromedriver"
driver = webdriver.Chrome(path) 

url= "https://news.naver.com/main/list.naver?mode=LS2D&mid=shm&sid1=101&sid2=259"
driver.get(url)

#sleep 사용해서 특정 시간대에 계속 불러올 수 있도록 설정가능
## css_selector로 불러오기 
ulsel="#main_content > div.list_body.newsflash_body > ul.type06_headline > li"
test= driver.find_elements_by_css_selector(ulsel)
for j in test: 
    print(j.test)

## Class 명으로 불러오기 
#type06_headlines =driver.find_elements_by_class_name("type06_headline")
#for i in type06_headlines: 
#    print(i.text)

# Selector 의 nth child for 문으로 반복하기 
#for i in len(1,len(test)+1): 
#    head= driver.find_element_by_css_selector(ul+f"> li:nth-child({i}) > div.cluster _text > a ") 
#    head.text


title = driver.execute_script('return document.title;')
title 
alert = driver.execute_script("alert('test');")

In [ ]:
##"OPEN WEATHER MAP" API Service 
# ID: ocdboi@gmail.com / PD: Qhpfrr132! 
# API Key: 0ff3eb790455ad8776100d61c8860db9
## Ex) GET Seoul, Tokyo, New York and print

# 필요한 Lib를 import 
import requests 
import json 

# API 키를 지정 
apikey= "0ff3eb790455ad8776100d61c8860db9"

# 날씨확인할 도시지정 
Cities= ["Seoul,KR", "Tokyo,JP","New York,US"]  
## 도시이름 어떻게 넣을지 확인하는 doc 

## API document 에서 제공하는 데이터 포멧설정 확인으로 List 작성이 가능하다. 
# http://bulk.openweathermap.org/sample.city.list.json.gz


api = "https://api.openweathermap.org/data/2.5/weather?q={City}&APPID={key}" 

#캘빈온도를 섭씨로 변환 
k2c= lambda k:k - 273.15

#각 도시의 정보추출 
for name in Cities:  
    # API요청할 URL 구성 
    url =api.format(City=name,key=apikey) 
    
    # API요청 
    re= requests.get(url)
    
    # 요청결과를 JSON으로 
    data= json.loads(re.text)
    
    # 출력결과확인 
    print(data) 
    print("----"*40)
    
    print("+도시 =",data["name"])
    print("|날씨 =",data["weather"][0]["description"])
    print("|최저기온 =",round(k2c(data["main"]["temp_min"]),1))
    print("|최고기온 =",round(k2c(data["main"]["temp_max"]),1)) 
    print("|습도=",data["main"]["humidity"]) 
    print("|기압=",data["main"]["pressure"]) 
    print("|풍향=",data["wind"]["deg"]) 
    print("|풍속=",data["wind"]["speed"])  
    print()

In [57]:
## API 들 
# https://www.apistore.co.kr/api/apiList.do OpenAPI스토어 
# https://developers.naver.com/main/ 네이버 개발자센터 
# https://developers.kakao.com/ #카카오 개발자센터 

# https://www.data.go.kr/data/15043562/openapi.do "기상청_일기도 데이터"에서 실제 요청값을 불러와라 

import requests
import json

url = 'http://apis.data.go.kr/1360000/WthrChartInfoService/getSurfaceChart'
key= "qlsGnZCjo3BEQmxXEkxUyR8x0kzA3FXE+TDftKG5ik2ba7LAkaXLdX4hAe2IlIUWuD3CfL5B3MfhGeLPWrk1Gw=="
params ={'serviceKey' : key, 'pageNo' : '1', 'numOfRows' : '15', 'dataType' : 'XML', 'code' : '50', 'time' : '20220515' }

response = requests.get(url, params=params)

print(response.text)

<?xml version="1.0" encoding="UTF-8"?>
<response><header><resultCode>00</resultCode><resultMsg>NORMAL_SERVICE</resultMsg></header><body><dataType>XML</dataType><items><item><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051500.png</man-file><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051503.png</man-file><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051506.png</man-file><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051509.png</man-file><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051512.png</man-file><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051515.png</man-file><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051518.png</man-file><man-file>http://www.kma.go.kr/repositary/image/cht/img/sfc3_2022051521.png</man-file></item></items><numOfRows>15</numOfRows><pageNo>1</pageNo><totalCount>8</totalCount></body></response>

In [76]:
## 다양한 데이터 형식
# 1.XML (Extensible Markup Language)
# : 범용적 데이터 형식으로 W3C에서 만듬. 
# 계층구조로 데이터를 표현할 수 있다는 특징 
# 기본구조: <요소 속성= "속성값"> 내용 </요소> 

# ex) 
# <products type= "전자제품">
#   <product id="S001" price= "45000">SD카드 128GB</product> 
#   <product id="S002" price= "32000">마우스 </product> 
# </products>  

# https://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnld=108 (전국육상예보) 

from bs4 import BeautifulSoup 
import urllib.request as req 
import os.path  

# XML 다운로드 
url= "https://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnld=108"
savename= "forecast.xml" 
if not os.path.exists("data/" +savename):
    req.urlretrieve(url,"data/"+savename)

# BeautifulSoup으로 분석 
xml = open("data/"+savename,"r", encoding= "utf-8")
soup= BeautifulSoup(xml,'html.parser')

# 각 지역별 정보확인
info = {} ##지역정보를 저장할 공간 

for location in soup.find_all("location"): 
    name= location.find('city').string 
    weather= location.find('wf').string
    if not (weather in info): 
        info[weather]=[]
    info[weather].append(name) 
info 

#각 지역별 날씨를 구분해서 출력해보자 
for weather in info.keys():
    print("+",weather) 
    for name in info[weather]: 
        print("| -",name )
    
    
# len(soup.find_all("location"))

+ 구름많음
| - 서울
| - 인천
| - 수원
| - 파주
| - 이천
| - 평택
| - 춘천
| - 원주
| - 대전
| - 세종
| - 홍성
| - 청주
| - 충주
| - 영동
| - 광주
| - 목포
| - 여수
| - 순천
| - 광양
| - 나주
| - 전주
| - 군산
| - 정읍
| - 남원
| - 고창
| - 무주
| - 부산
| - 울산
| - 창원
| - 진주
| - 거창
| - 통영
| - 제주
| - 서귀포
+ 맑음
| - 강릉
| - 대구
| - 안동
| - 포항
| - 경주
| - 울진
| - 울릉도

In [ ]:
##JSON의 구조 
# https://www.json.org/json-ko.html
# Key값 벨류값, 파이썬에서는 딕셔너리와 유사, 

##YAML 분석
#: 들여쓰기를 사용해서 계층구조를 표현하는 것이 특징인 데이터 형식
# XML보다 간단하고 거의 JSON과 비슷하다. 
# 파이썬에서 YAML을 다루기 위해서는 PyYAML 이라는 모듈설치필요
# pip install PyYAML 

# YAML 예제 
import yaml 

# YAML 예제 
yaml_str = """  
Date: 2022-05-16
PriceList:
    - 
        item_id: 1000
        name: Banana
        color: yellow 
        price: 1000
    -   
        item_id: 1001 
        name: Orange
        color: orange 
        price: 1400 
    -
        item_id: 1002  
        name: Apple 
        color: red 
        price: 2000
""" 

#yaml 분석 
data1 = yaml.full_load(yaml_str)
print(data1)
data2 = yaml.safe_load(yaml_str) # load() 보안상 이유로 경고가 발생

# 이름, 가격 출력
for item in data2['PriceList']: 
    print(item['name'],item['price'])

In [ ]:
import yaml 

# 파이썬 데이터를 yaml데이타 출력 
customer = [ 
            {"name":"InSeong","age":"24","gender":"man"},
            {"name":"gilja","age":"22","gender":"woman"},
            {"name":"sunshin","age":"31","gender":"woman"},
            {"name":"bangown","age":"23","gender":"man"}
            ]

# YAML 데이터로 변환 
yaml_str1= yaml.dump(customer)
print(yaml_str1)

data = yaml.safe_load(yaml_str1)

for p in data: 
    print(p['name'])

In [96]:
## YAML의 기본은 배열, 해시, 스칼라(문자열, 숫자, 불리언) 
# 배열을 나타낼때는 각 행의 앞에 하이픈(-)을 붙인다. 하이픈 뒤에는 공백이 필요함

## 예시(배열) 
# -banana 
# -kiwi 
# -mango 

## 예시(중첩배열), 들여쓰기 다음에 바로 빈 요소를 사용함. 
#- Yellow 
#-
#    -Banana 
#    -Orange
#- Red 
#-
#    -Apple
#    -StrawBerry

##해시표현("<키>:<값>"), 해시표현시에도 들여쓰기를 사용하여 계층구조를 표현  
#name: Gurum
#age: 4
#color: brown

## YAML의 주석은 "#"

## YAML에서 여러줄 문자열을 지정하는 방법 
#multi-line: 
#    I like Banana 
#    I like Mango 
#    I like Orange  


## YAML 의 앵커와 별칭을 지원 
# "&<이름>" 형태로 변수를 선언, "*<이름>" 형태로 참조 

# 색 정의 
#color_define: 
#    - &color1 "#FF0000"
#    - &color2 "#00FF00" 
#    - &color3 "#00FFFF" 

# 색 설정 
#frame_color: 
#    title: *color1 
#    logo: *color2 
    
#article_color:
#    title: *color2
#    back: *color3

import yaml 
# 문자열로 yaml을 정의
yaml_str = """ 
#색정의 
color_def: 
    - &color1 "#FF0000"
    - &color2 "#00FF00" 
    - &color3 "#00FFFF" 

#색설정(별칭)
color: 
    title: *color1 
    body: *color2
    link: *color3
""" 
# YAML로 데이터로 분석
data = yaml.safe_load(yaml_str) 

# 별칭확인 테스트
print("title=",data["color"]["title"])
print("body=",data["color"]["body"])
print("link=",data["color"]["link"])

title= #FF0000
body= #00FF00
link= #00FFFF

In [136]:
## Excel 데이터 읽기
import openpyxl 

filename = "stat_100701.xlsx" 
book = openpyxl.load_workbook("data/"+filename) 

# 맨앞의 시트(Sheet)추출 
sheet = book.worksheets[0] 

# 시트의 각 행을 순서대로 추출 
data = [] 
for row in sheet.rows:
    data.append([
        row[0].value,
        row[4].value
        ])
# 필요없는 줄(헤더, 연도, 계) 제거하기 
del data[0:5] 
del data[-4:]

# 데이터를 인구순서대로 정렬 
# data = sorted(data, key= lambda x:int(x[1].replace(',','')))
data= sorted(data, key=lambda x: x[1])
print(data)

# 하위 5위까지 출력 
for i , a in enumerate(data): 
    if(i>=5): break
    print(i+1,a[0],int(a[1]))

[['세종', 349], ['제주', 670], ['울산', 1140], ['광주', 1488], ['대전', 1500], ['강원', 1515], ['충북', 1632], ['전남', 1764], ['전북', 1792], ['충남', 2204], ['대구', 2419], ['경북', 2655], ['인천', 2951], ['부산', 3344], ['경남', 3350], ['서울', 9602], ['경기', 13405], ['수도권', 25958]]
1 세종 349
2 제주 670
3 울산 1140
4 광주 1488
5 대전 1500

In [131]:
import pandas 
filename = "stat_100701.xlsx" 
data_test= pandas.read_excel("data/"+filename,"Sheet0") 
data_test

,통계표명:,지역별 인구 및 인구밀도,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,단위:,"천명, 명/㎢",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2017,NaN,2018,NaN,2019,NaN,2020,NaN
2,NaN,인구,인구밀도,인구,인구밀도,인구,인구밀도,인구,인구밀도
3,계,51362,512,51607,514,51709,515,51781,516
4,서울,9766,16136,9705,16034,9662,15964,9602,15865
5,부산,3424,4447,3400,4416,3373,4380,3344,4342
6,대구,2458,2782,2450,2773,2432,2753,2419,2738
7,인천,2924,2750,2939,2764,2944,2769,2951,2770
8,광주,1495,2984,1493,2980,1494,2980,1488,2969
9,대전,1528,2832,1518,2813,1509,2796,1500,2780
10,울산,1159,1092,1154,1088,1147,1080,1140,1073
11,세종,266,571,304,653,331,712,349,750
12,경기,12786,1255,13031,1279,13238,1299,13405,1315
13,강원,1521,90,1521,90,1517,90,1515,90
14,충북,1609,217,1619,219,1626,219,1632,220
15,충남,2153,262,2180,265,2188,265,2204,267
16,전북,1829,227,1820,226,1803,223,1792,222
17,전남,1795,146,1790,145,1773,144,1764,143
18,경북,2675,141,2674,141,2665,140,2655,140
19,경남,3339,317,3356,318,3350,318,3350,318
20,제주,635,343,653,353,660,356,670,362
21,수도권,25476,2149,25675,2165,25844,2179,25958,2188
22,출처:,"통계청「장래인구추계 시도편 : 2017-2047」, 국토교통부「지적통계」",NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,주석:,"* 수도권 : 서울, 인천, 경기",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,* 통계청『장래인구추계 시도편 : 2017-2047』의 시도별 인구와 국토교통부『지...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,* 시도별 장래인구추계는 2019년에 작성된 자료임,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
## Excel 데이터 쓰기 
import openpyxl 

# 엑셀파일 열기 
filename = "stat_100701.xlsx" 
book = openpyxl.load_workbook("data/"+filename) 

# 활성화된 시트추출 
sheet= book.active 
# sheet 

# 서울을 제외한 인구를 구해서 쓰기 
test= sheet[str(chr(i+66))+"3"].value
for i in range(0,4): 
    total = int(sheet[str(chr(i+66))+"5"].value)
    seoul = int(sheet[str(chr(i+66))+"6"].value)
    output = total - seoul 
    print("서울제외인구=", output)
    print(total,seoul)
    print("-"*50)
    
    #쓰기 
    
    sheet[str(chr(i+66))+"24"]= output
    cell = sheet[str(chr(i+66))+"24"]
    
    #폰트색상변경
    cell.font = openpyxl.styles.Font(size=14, color="FF0000") 
    cell.number_format = cell.number_format 
  

sheet[str(chr(65))+"24"] = "서울제외인구"
  
# 엑셀파일 저장하기 
filename = "population.xlsx" 
book.save(filename)

서울제외인구= 41596
51362 9766
--------------------------------------------------
서울제외인구= 41902
51607 9705
--------------------------------------------------
서울제외인구= 42047
51709 9662
--------------------------------------------------
서울제외인구= 42179
51781 9602
--------------------------------------------------